POC for adding new task : add via simple form
theodo/captain-staffing pull request #26
Opened 2017-12-12 23:04 UTC by invfo

<img width="1416" alt="capture d ecran 2017-12-13 a 00 03 10" src="https://user-images.githubusercontent.com/10657271/33913197-27df3016-df99-11e7-94e4-ba3729a63505.png">
<img width="1418" alt="capture d ecran 2017-12-13 a 00 02 58" src="https://user-images.githubusercontent.com/10657271/33913198-27faa530-df99-11e7-8f76-6eee7806b381.png">

Les bases de redux (actions et reducers):

- https://redux.js.org/docs/basics/Actions.html
- https://redux.js.org/docs/basics/Reducers.html

2017-12-12 23:56 UTC, benja-M-1 requested changes

2017-12-12 23:56 UTC, benja-M-1 commented on src/components/Staffing/Staffing.component.js
> +  handleSubmit(event) {
tu peux utiliser ```handleSubmit = (event) => {...}``` pour éviter le binding ligne 132 stp ?

2017-12-12 23:56 UTC, benja-M-1 commented on src/components/Staffing/Staffing.component.js
> +  handleChange(event) {
tu peux utiliser ```handleChange = (event) => {...}``` pour éviter le binding ligne 131 stp ?

2017-12-12 23:56 UTC, benja-M-1 commented on src/components/Staffing/Staffing.component.js
> +class NewTaskForm extends React.Component<Props> {
Pour qu'on garde des composants découplé et qu'on applique les standards Theodo, est-ce que tu peux en faire un composant à part qui suit le standard index.js + container + component ?

2017-12-12 23:56 UTC, benja-M-1 commented on src/store.js
> +  if (typeof state === 'undefined') {
Pour éviter ce check tu peux utiliser des paramètres par défaut : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2017-12-12 23:56 UTC, benja-M-1 commented on src/store.js
> +function staffingReducer(state, action) {
je suis pas hyper au fait des standards à propos de où devrait se placer les reducers (still learning ;)), mais est-ce que ce ne serait pas mieux de le mettre dans le composant NewTask ?

2017-12-12 23:56 UTC, benja-M-1 commented on src/store.js
> +      return Object.assign({}, state, {timeline: state.timeline.concat([action.task])});
Je ne sais plus pourquoi mais @ghamaide m'a conseillé d'utiliser le spread operator : ```return { ...state, { timeline: state.timeline.concat([action.task] } }```. Tu préfères pas ?

2017-12-12 23:56 UTC, benja-M-1 commented on src/components/Staffing/Staffing.component.js
> +  createRows(timeline=this.props.timeline) {
tu peux rajouter des espaces avant et après le ```=``` ?

2017-12-12 23:57 UTC, benja-M-1 commented
@invfo je me demandes si tu as bien configuré ton IDE, tu utilises vscode ? dans ce cas je te conseille d'installer le theodo-extension-pack http://blog.m33.network/2017/09/how-to-set-up-correctly-your-ide-text-editor-for-efficient-developing/ :)

2017-12-12 23:58 UTC, benja-M-1 commented
En ce qui concerne le store, les reducers, etc... j'ai une PR en cours. Je vais la pousser pour que tu vois ce que je suis en train de faire et que tu me donnes ton avis :)

2017-12-13 07:46 UTC, ghamaide commented on src/store.js
> +      return Object.assign({}, state, {timeline: state.timeline.concat([action.task])});
@benja-M-1 C'est plus lisible je trouve. Je vous conseille de mettre en place prettier sur le projet. Avec un `formatOnSave: true`, plus de questions à se poser. Pareil pour cette règle, tu utilises un plugin eslint qui te convertira ton Object.assign automatiquement: cf https://github.com/theodo/theodo-stack-generator/pull/47#issuecomment-343157613

2017-12-21 20:54 UTC, invfo commented
@benja-M-1 j'ai rebase la branche sur la tienne et j'ai pris en compte toutes les remarques! :-)

2017-12-22 01:52 UTC, benja-M-1 commented on src/entities/Tasks/actions.js
> +export const addTask = (task) => ({
il n'existe pas de convention pour le nom des reducers ?

2017-12-22 18:59 UTC, invfo commented on src/entities/Tasks/actions.js
> +export const addTask = (task) => ({
Pour les action creators (le morceau que tu a commenté) le nommage conseillé est <verb><Noun>, ce qu'on respecte.
Plus d'info: https://medium.com/@kylpo/redux-best-practices-eef55a20cc72

2018-02-15 21:58 UTC, merged